NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/org2-ca-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/org2-ca-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/org2-ca-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/org2-ca-cert.pem
    OrganizationalUnitIdentifier: orderer

